// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryycjmitvqpvgnnszeyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5eWNqbWl0dnFwdmdubnN6ZXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjEyNDMsImV4cCI6MjA1NDY5NzI0M30.SKCy08pugOG1sADgFET8Xwhzn5aB2YePwu87Yco3hkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);